version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <your_aws_account_id>.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - docker build -t gangwar-ecr-repo .
      - docker tag gangwar-ecr-repo:latest <your_aws_account_id>.dkr.ecr.us-east-1.amazonaws.com/gangwar-ecr-repo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push <your_aws_account_id>.dkr.ecr.us-east-1.amazonaws.com/gangwar-ecr-repo:latest
artifacts:
  files: '**/*'
